cloudflare/env.go
cloudflare/kv.go
cloudflare/r2bucket.go
cloudflare/runtimecontext.go
examples/basic-auth-proxy/worker.mjs
examples/env/main.go
examples/env/worker.mjs
examples/hello/worker.mjs
examples/kv-counter/main.go
examples/kv-counter/worker.mjs
examples/r2-image-server/main.go
examples/r2-image-server/worker.mjs
examples/r2-image-viewer/main.go
examples/r2-image-viewer/worker.mjs
examples/simple-json-server/app/app_easyjson.go
examples/simple-json-server/worker.mjs
handler.go
internal/runtimecontext/context.go

* add runtime context.
- runtime context holds runtime specific (like Cloudflare, Deno Deploy) context values.
* This change affects to current cloudflare package's implementations to force to get value from `req.Context()`.
```diff
func main() {
handler := http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
-		fmt.Fprintf(w, "MY_ENV: %s", cloudflare.Getenv("MY_ENV"))
+		fmt.Fprintf(w, "MY_ENV: %s", cloudflare.Getenv(req.Context(), "MY_ENV"))
})
workers.Serve(handler)
}
```

add runtime context

---

cloudflare/d1/rows.go
cloudflare/d1/rows_test.go
examples/d1-blog-server/app/handler.go

* When D1 driver row returns a Number value, this was always converted as float64.
* To add ability to `Scan` on integral type variables, treat integral float64 value as int64.
- int64 is enough large to store an integral Number value (2^63-1 > 2^53-1).

treat D1 driver row's integral float64 value as int64

---

cloudflare/dostub.go

This is a tiny PR, fixing broken reference to `getRuntimeContextEnv` when using code in the `cloudflare` directory.

Fix reference to getRuntimeContextEnv

---

cloudflare/cache/method.go
handler.go
internal/jshttp/response.go
internal/jshttp/responsewriter.go

* commonize ToJSResponse func.
* move `<-w.Ready` to outside of ToJSResponse func.
Because the cache package and jshttp package share almost the same logic for response conversion.

commonize ToJSResponse func logic

---

handler.go
internal/jshttp/responsewriter.go

* Rename ResponseWriterBuffer to ResponseWriter
* Because it doesn't provide `buffer` functionality and is just a ResponseWriter of jshttp.

rename ResponseWriterBuffer to ResponseWriter

---

README.md
cloudflare/cron/cron.go
examples/cron/main.go

* split cron package and moved into cloudflare package.
* rename some types in cron package.
- because it includes `cron` in package name.
* `Cron Trigger` feature is considered as `cloudflare` specific feature, so it's better to be placed in cloudflare package.

move cron into cloudflare

---

_examples/pages-functions/Makefile
_examples/pages-functions/functions/hello.js
_examples/pages-functions/wrangler.toml
cmd/workers-assets-gen/assets/common/shim.mjs

* add `onRequest` handler to shim.mjs and exported it.
* use `workers-assets-gen` command in pages functions example.
* To resolve #50.

use workers-assets-gen command in pages functions example

---

_templates/cloudflare/pages-tinygo/Makefile
_templates/cloudflare/pages-tinygo/README.md
_templates/cloudflare/pages-tinygo/functions/api/[[routes]].mjs
_templates/cloudflare/pages-tinygo/go.mod
_templates/cloudflare/pages-tinygo/go.sum
_templates/cloudflare/pages-tinygo/main.go
_templates/cloudflare/pages-tinygo/pages/index.html
_templates/cloudflare/pages-tinygo/wrangler.toml

Added pages and functions tinygo template for use with wrangler generate.
[Github issue to add template](https://github.com/syumai/workers/issues/51)
I was unable to test yet due to being unsure how to test wrangler generate with an alternative branch or local template. 
I also deleted go.mod and go.sum as go.mod referenced the old example module and the other templates did not have these. I'm unsure if this will affect the template or if it will affect go-chi being automatically installed.

added pages template

---

_templates/cloudflare/pages-tinygo/README.md
_templates/cloudflare/pages-tinygo/go.mod
_templates/cloudflare/worker-go/README.md
_templates/cloudflare/worker-go/go.mod
_templates/cloudflare/worker-tinygo/README.md
_templates/cloudflare/worker-tinygo/go.mod

* Replace initialization command `wrangler generate` to `gonew`.
* `wrangler generate` has been deprecated.
* `gonew` command seemed appropriate for this use case.
- https://go.dev/blog/gonew

use gonew command to initialize project

---

_templates/cloudflare/pages-tinygo/go.mod
_templates/cloudflare/pages-tinygo/go.sum

* pages example had too much information.
- removed unnecessary information
* `go mod tidy` is not working as expected.

fix pages example's go.mod

---

_templates/cloudflare/pages-tinygo/Makefile
_templates/cloudflare/worker-go/Makefile
_templates/cloudflare/worker-tinygo/Makefile

update workers-assets-gen cmd in examples to v0.20.0.
* performance API polyfill has been removed from generated files.

update workers-assets-gen cmd in examples to v0.20.0

---

cmd/workers-assets-gen/assets/common/shim.mjs
handler.go

* use  go:wasmimport for ready func which is called by `workers.Serve()`.
* To reduce use of `js.Global()`.

use go:wasmimport for ready func

---

cloudflare/d1/stmt.go

I fixed an issue where the D1 driver would cause a panic when QueryContext is called with parameters.
The problem was that QueryContext was attempting to bind driver.NamedValue as JavaScript values, which was bound to fail.
I have updated it to bind driver.NamedValue.Value in the same way that ExecContext does.
Thank you for providing such a wonderful framework.
I hope this fix will be helpful to you.

D1 driver would cause panic when QueryContext is called with parameters

---

cmd/workers-assets-gen/assets/common/shim.mjs
handler.go
internal/jshttp/responsewriter.go

* initialize Go instance on Request.
- This resolves `call to released function` error.
* add `closeCh` to main.go.
- This reduces `all goroutines are asleep - deadlock!` error.
* To improve app stability.

init Go instance on request

---

_examples/stream-large-file/.gitignore
_examples/stream-large-file/Makefile
_examples/stream-large-file/README.md
_examples/stream-large-file/go.mod
_examples/stream-large-file/go.sum
_examples/stream-large-file/main.go
_examples/stream-large-file/wrangler.toml
cloudflare/fetch/bind.go

The `fetch` package causes a memory limit error when receiving a large response. In such cases, cloudflare recommends using `TransformStream`.

Support stream in fetch pkg

---

_templates/cloudflare/worker-go/wrangler.toml

Update the `compatibility_date` and remove the need for https://developers.cloudflare.com/workers/configuration/compatibility-dates/#streams-constructors as it is the default as of `2022-11-30`
Clearer for new users + ensures that new Workers features are adopted with the new compat date.

build: update compat date, remove

---

.github/workflows/pull_request.yaml
Makefile
_examples/service-bindings/main.go

add Makefile command and GH workflow job to build example files
For detecting broken examples.

add Makefile command to build example files

---

handler.go
internal/jsutil/jsutil.go
internal/jsutil/stream.go

fix handler error handlings

---

cloudflare/d1/rows.go
cloudflare/d1/stmt.go

fix D1 driver implementation using stmt.raw({ columnNames: true })

---

handler.go
handler_without_js.go

* This PR adds normal HTTP server listener for debugging purposes.
* With this feature, the example below works using only the `go run` command without `GOOS` and `GOARCH`.
```go
package main
import (
"fmt"
"net/http"
"github.com/syumai/workers"
)
func main() {
handler := http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
fmt.Fprint(w, "Hello, world!")
})
workers.Serve(handler)
}
```
* To make development easier for developers who are not familiar with JS/Wasm.

add normal HTTP server listener for debugging purposes

---

cloudflare/fetch/property.go
internal/jsutil/jsutil.go

Adds a MaybeInt js.Value wrapper to jsutil.
Cloudflare sometimes provides a `cf` object with no `asn` key. This causes cloudflare/fetch.NewIncomingProperties() to panic. This is described in #119.
This change adds a js.Value wrapper for ints which first verifies if the Value is undefined.

add jsutil.MaybeInt wrapper; apply it to IncomingProperties.Asn

---

cloudflare/fetch/bind.go
internal/jshttp/response.go

* Stopped using `ToStreamResponse` in fetch func and replaced it to `ToResponse`.
* Current implementation of fetch panics when fetch result body is empty (No Content).
- #122
* The piping logic to TransformStream is causing this issue.
- Stream responses without TransformStream piping are already working since the following commit: https://github.com/syumai/workers/commit/bf3ab8ec410eed5ba7c8bb2da3aa41fd769adb20.
- Therefore, I've stopped using TransformStream piping.

fixed panic on fetch returning empty response

---

_examples/queues/.gitignore
_examples/queues/Makefile
_examples/queues/README.md
_examples/queues/go.mod
_examples/queues/main.go
_examples/queues/wrangler.toml
cloudflare/queues/content_type.go
cloudflare/queues/content_type_test.go
cloudflare/queues/producer.go
cloudflare/queues/producer_opts.go
cloudflare/queues/producer_test.go
internal/jsutil/jsutil.go

This PR implements the producer side of the [Cloudflare Queues](https://developers.cloudflare.com/queues/configuration/javascript-apis/) feature.
#53

Add message producer

---

cloudflare/cron/scheduler.go

Fixes #127
Add a non-blocking version of `cron.ScheduleTask` so that it can be called before `workers.Serve`, allowing a single WASM binary to handle both cron triggers and HTTP requests
See #127

Support HTTP Request and Cron Trigger in Single Worker

---

_examples/cron/Makefile
_examples/cron/README.md
_examples/cron/main.go
_examples/multiple-handlers/.gitignore
_examples/multiple-handlers/Makefile
_examples/multiple-handlers/README.md
_examples/multiple-handlers/go.mod
_examples/multiple-handlers/main.go
_examples/multiple-handlers/wrangler.toml
cloudflare/cron/scheduler.go
handler.go
handler_js.go

* Add `workers.ServeNonBlock`, `workers.Done`, `workers.Ready` and `cron.Done` funcs.
* #130 introduced a non-blocking version of `cron.ScheduleTask`.
- A non-blocking version of `workers.Serve` is also needed, so this PR adds it.
* Additionally, the `workers` package provides a public `Ready()` function.
- It can be used as a common ready signal function.
* The `Done()` function can be used to wait for a handler or a task to complete.
```go
func main() {
// declare handler and task here ...
// set up the worker
workers.ServeNonBlock(handler)
cron.ScheduleTaskNonBlock(task)
// send a ready signal to the runtime
workers.Ready()
// block until the handler or task is done
select {
case <-workers.Done():
case <-cron.Done():
}
}
```

split Done funcs from workers.Serve / cron.ScheduleTask

---

_examples/r2-image-server/main.go
_examples/r2-image-viewer/main.go
cloudflare/r2.go
cloudflare/r2/bucket.go
cloudflare/r2/object.go
cloudflare/r2/objects.go
cloudflare/r2bucket.go
cloudflare/r2object.go
cloudflare/r2objects.go

* Move R2 related features to the cloudflare/r2 package.
* Consistency with the implementation of other features.

move r2 features to cloudflare/r2 package

---

_examples/queues/README.md
_examples/queues/main.go
_examples/queues/wrangler.toml
cloudflare/queues/consumer.go
cloudflare/queues/consumermessage.go
cloudflare/queues/consumermessage_test.go
cloudflare/queues/consumermessagebatch.go
cloudflare/queues/consumermessagebatch_test.go
cloudflare/queues/retryoptions.go
cmd/workers-assets-gen/assets/common/shim.mjs
cmd/workers-assets-gen/assets/common/worker.mjs
internal/jsutil/jsutil.go

This adds support for Queues consumer.
#53

Implement Queues Consumer

---

_examples/queues/README.md
_examples/queues/main.go
cloudflare/queues/consumer.go

Renamed ConsumeNonBlocking to ConsumeNonBlock.
To maintain consistency with `workers.ServeNonBlock` and similar cases.

rename ConsumeNonBlocking to ConsumeNonBlock

---

cloudflare/queues/batchmessage.go
cloudflare/queues/producer.go
cloudflare/queues/producer_test.go

* The original name, BatchMessage, was inconsistent with Cloudflare's type definition.
* I changed its name to match Cloudflare's type definition.
* To reduce the difference in usage experience compared to Cloudflare's official library.

Rename BatchMessage to MessageSendRequest

---

README.md
_templates/cloudflare/cron-go/Makefile
_templates/cloudflare/cron-tinygo/Makefile
_templates/cloudflare/pages-tinygo/Makefile
_templates/cloudflare/worker-go/Makefile
_templates/cloudflare/worker-tinygo/Makefile
cmd/workers-assets-gen/assets/wasm_exec_go.js
cmd/workers-assets-gen/assets/wasm_exec_tinygo.js

* update wasm_exec.js contents.
* Go 1.24 has been released, and its wasm_exec.js file has been updated.

update wasm_exec.js contents

---

_templates/cloudflare/cron-go/Makefile
_templates/cloudflare/cron-tinygo/Makefile
_templates/cloudflare/pages-tinygo/Makefile
_templates/cloudflare/worker-go/Makefile
_templates/cloudflare/worker-tinygo/Makefile

* remove version from `workers-assets-gen` command calls in templates.
* It was unnecessary.
- `workers-assets-gen` command should be same version with `syumai/workers` module in `go.mod`.
- `go run` selects module version from `go.mod`.
- [docs](https://go.dev/ref/mod#:~:text=In%20module%2Daware%20mode%2C%20the%20go%20command%20uses%20go.mod%20files%20to%20find%20versioned%20dependencies%2C%20and%20it%20typically%20loads%20packages%20out%20of%20the%20module%20cache%2C%20downloading%20modules%20if%20they%20are%20missing.)

remove version from workers-assets-gen command call

---

cmd/workers-assets-gen/assets/common/shim.mjs
cmd/workers-assets-gen/assets/runtime/cloudflare.mjs
cmd/workers-assets-gen/main.go
cmd/workers-assets-gen/runtime.go

* split `import { connect } from "cloudflare:sockets";` to `assets/runtime/cloudflare.mjs`.
* To support other runtimes.

split runtime param of workers-assets-gen command

---

_examples/browser/.gitignore
_examples/browser/README.md
_examples/browser/go.mod
_examples/browser/main.go
_examples/browser/package-lock.json
_examples/browser/package.json
_examples/browser/public/index.html
_examples/browser/public/index.mjs
_examples/browser/wrangler.jsonc
cmd/workers-assets-gen/assets/runtime/browser.mjs
cmd/workers-assets-gen/runtime.go

* Added new example to run Go HTTP Server on the browser.
- https://browser-example.syumai.workers.dev/

add browser support

---

_examples/hello/Makefile
_examples/hello/README.md
internal/jshttp/response.go
internal/jsutil/jsutil.go
internal/jsutil/stream.go

* Add an existence check for FixedLengthStream.
- Because the browser environment (added recently) doesn't have it.
* Add a `ready` check to write calls to the WritableStream of FixedLengthStream.
- See: https://developer.mozilla.org/en-US/docs/Web/API/WritableStream#backpressure
To fix https://github.com/syumai/workers/issues/101#issuecomment-2718681263

fix bug of FixedLengthTransformStream

---

internal/jshttp/request.go

* Changed code to return an empty ReadCloser when request body is nil.
* Without this change, if a handler attempts to access Request.Body when it's nil, the application would panic. This fix prevents the crash and provides a proper empty reader instead.

return empty ReadCloser for nil request body
